# version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-nest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_crm
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_crm"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: